AWSTemplateFormatVersion: 2010-09-09
Description: Lambda execution role for scheduled backups
Parameters:
  RoleName:
    Type: String
    Description: Name of the role
    MinLength: '1'
    MaxLength: '255'
    Default: 'ebs-lambda-worker'
    
Resources:
  Role:
    Type: 'AWS::IAM::Role'
    Properties:
      Path: '/'    
      Policies:
        - PolicyName: snapshot-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: 
                  - 'logs:*'
                Resource: 'arn:aws:logs:*:*:*'
              
              - Effect: Allow
                Action:
                  - 'ec2:Describe*'
                Resource: '*'

              - Effect: Allow
                Action:
                  - 'ec2:CreateSnapshot'
                  - 'ec2:DeleteSnapshot'
                  - 'ec2:CreateTags'
                  - 'ec2:ModifySnapshotAttribute'
                  - 'ec2:ResetSnapshotAttribute'
                Resource: '*'

      RoleName: !Ref RoleName